---
- name: Cleanup old backup directory
  file: dest={{ influxdb_backup_dir }} state=absent

- name: Backup the database
  command: "influxd backup -portable -db {{ item }} {{ influxdb_backup_dir }}"
  with_items: "{{ influxdb_backup_databases }}"

- name: Ensure azure blob storage container exists
  command: az storage container create  --name "{{azure_influxdb_backup_container}}" --public-access blob

- name: zip the backup dir
  archive:
    path: "{{ influxdb_backup_dir }}"
    dest: "{{ influxdb_backup_dir }}/{{ influxdb_backup_file_name }}.zip"
    format: zip

- name: Upload the backup to azure blob storage
  #command: az storage blob upload --name "{{ influxdb_backup_file_name }}".zip --file "{{ influxdb_backup_dir }}/{{ influxdb_backup_file_name }}".zip --container-name {{ azure_influxdb_backup_container }}
  command: az storage blob upload -c "{{ azure_influxdb_backup_container }}" --name "{{ influxdb_backup_file_name }}".zip -f "{{ influxdb_backup_dir }}/{{ influxdb_backup_file_name }}".zip

- name: upload file to gcloud storage
  include_role:
    name: gcp-cloud-storage
    tasks_from: upload.yml
  vars:
    gcp_bucket_name: "{{ gcloud_management_bucket_name }}"
    dest_folder_name: "{{ influxdb_backup_storage }}"
    dest_file_name: "{{ influxdb_backup_file_name }}".zip
    local_file_or_folder_path: "{{ influxdb_backup_dir }}/{{ influxdb_backup_file_name }}".zip
  when: cloud_service_provider == "gcloud"
